# Generated by Django 3.0 on 2020-05-26 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200526_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderResponse',
            fields=[
                ('response', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGoods',
            fields=[
                ('type_of_goods', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('type_of_goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.TypeOfGoods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=5000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000)),
                ('addition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.AdditionProduct')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Order')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.OrderResponse')),
            ],
        ),
        migrations.AddField(
            model_name='additionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Product'),
        ),
        migrations.AddField(
            model_name='additionproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
