# Generated by Django 3.0 on 2020-05-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200526_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='users.TypeOfGoods'),
            preserve_default=False,
        ),
    ]
