# Generated by Django 3.0 on 2020-05-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200530_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyorders',
            name='addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.AdditionProduct'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Order'),
        ),
    ]
