# Generated by Django 3.0 on 2020-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200530_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='(29)111-11-11', max_length=13, null=True),
        ),
    ]
