# Generated by Django 3.0 on 2020-05-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_type_of_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_goods',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TypeOfGoods'),
        ),
    ]
