# Generated by Django 3.0 on 2020-05-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200527_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofgoods',
            name='type_of_goods',
            field=models.CharField(default='Horica and Event', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TypeOfGoods'),
        ),
    ]
