# Generated by Django 3.0 on 2020-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200601_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='80291111111', max_length=13, null=True),
        ),
    ]
