# Generated by Django 3.0 on 2020-05-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200527_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_goods',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
