# Generated by Django 3.0 on 2020-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200602_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='00000000000', max_length=13, null=True),
        ),
    ]
