# Generated by Django 3.0 on 2020-05-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200528_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TypeOfGoods'),
        ),
    ]
