# Generated by Django 3.0 on 2020-06-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200603_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Product'),
        ),
        migrations.AlterField(
            model_name='additionproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AdditionProduct'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Order'),
        ),
        migrations.AlterField(
            model_name='historyorders',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.OrderResponse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TypeOfGoods'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TypeOfGoods'),
        ),
    ]
